/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Logo: typeof import('./src/components/Icons/logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    STHeader: typeof import('./src/components/STHeader/STHeader.vue')['default']
    STMetaHeader: typeof import('./src/components/STMetaHeader/STMetaHeader.vue')['default']
  }
}
