/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconLogo: typeof import('./src/components/st-icons/IconLogo.vue')['default']
    Logo: typeof import('./src/components/Icons/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    STChart: typeof import('./src/components/st-chart/STChart.vue')['default']
    STChat: typeof import('./src/components/st-chat/STChat.vue')['default']
    STHeader: typeof import('./src/components/st-header/STHeader.vue')['default']
    STMetaHeader: typeof import('./src/components/st-meta-header/STMetaHeader.vue')['default']
    STPrint: typeof import('./src/components/st-print/STPrint.vue')['default']
    STTable: typeof import('./src/components/st-table/STTable.vue')['default']
  }
}
